# Generated by Django 5.2 on 2025-04-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="detail",
            field=models.TextField(default=""),
        ),
    ]
