# Generated by Django 5.2 on 2025-05-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_task_created_at_task_due_date_task_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="detail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="place",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
